mqtt:
  server:
    enabled: true
    name: Mica-Mqtt-Server
    ip: 127.0.0.1
    port: 5883
    buffer-allocator: HEAP
    heartbeat-timeout: 120000 # 心跳超时，单位毫秒
    read-buffer-size: 8092
    max-bytes-in-message: 8092
    debug: true
  client:
    enabled: true
    name: Mica-Mqtt-Client
    ip: 127.0.0.1
    port: 3883
    user-name: mica
    password: 123456
    timeout: 5 # 单位：秒，默认：5秒
    readBufferSize: 8092
    keepAliveSecs: 60 # 单位秒
    reconnect: true
    reInterval: 5000 # 重连重试时间，单位：毫秒，默认：5000
    clientId: 000001
    cleanSession: true
    version: MQTT_5
    bufferAllocator: HEAP
