spring:
  application:
    name: mica-mqtt-server
  profiles:
    active: server
springdoc:
  swagger-ui:
    urls:
      - name: swagger
        url: /v3/api-docs
# actuator management
management:
  info:
    defaults:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    server: info # t-io 服务端默认日志
    org.tio: info # t-io 服务端默认日志
