spring:
  application:
    name: mica-mqtt-client
  profiles:
    active: client
springdoc:
  swagger-ui:
    urls:
      - name: swagger
        url: /v3/api-docs
logging:
  level:
    root: info
    server: info # t-io 服务端默认日志
    org.tio: info # t-io 服务端默认日志
